import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "This is Main screen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`p-2 w-full bg-[#F4F2EE]`}>
        <div className="w-full flex justify-center p-2 border rounded-md min-h-[calc(100vh-20px)]">
          <main className="w-full">
            <div className="bg-white mb-10 h-[50px] flex justify-center items-center">
              <div className=" w-full md:w-full lg:w-[90%] xl:w-[1150px]  ">
                <Header />
              </div>
            </div>
            <div className=" flex justify-center items-center">
              <div className=" w-full md:w-full lg:w-[90%] xl:w-[1150px]  ">
                {children}
              </div>
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
